### ISSUE TITLE
after PoW mining BTCSQ exists with code 134

### ISSUE THREAD

**Issue by Skemba** [VeriBlock/alt-integration-cpp#964] opened 2022-03-09 09:59 UTC

**Comment by Warchant** [comment] 2022-03-09 12:11
@Skemba do you have full debug.log?

**Comment by Skemba** [comment] 2022-03-09 13:26
[1.log.zip](https://github.com/VeriBlock/alt-integration-cpp/files/8215026/1.log.zip)

**Comment by Warchant** [comment] 2022-09-01 08:18
Closing, cannot reproduce.

**Closed by Warchant** 2022-09-01 08:18 UTC
